[versions]
detektPlugin = "1.23.8"
ideaExtPlugin = "1.3"
kotlinPlugin = "2.2.21"
kspPlugin = "2.3.4"
shadowPlugin = "9.3.1"

kotest = "6.0.7"
log4jApi = "2.25.3"
log4jApiKotlin = "1.5.0"
logback = "1.5.23"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektPlugin" }
ideaExt = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "ideaExtPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinPlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadowPlugin" }

[libraries]
detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektPlugin" }
kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotestRunnerJunit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
log4jApiKotlin = { module = "org.apache.logging.log4j:log4j-api-kotlin", version.ref = "log4jApiKotlin" }
log4jApiToSlf4j = { module = "org.apache.logging.log4j:log4j-to-slf4j", version.ref = "log4jApi" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
